name: Eze Github Actions for Sarif

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  eze-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    name: Eze Security Test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
#       - name: "Testing with Eze - sarif"
#         uses: RiverSafeUK/eze-docker-action@main
#         with: 
#           # Define the value of the upload format (sarif or markdown)
#           upload_method: sarif
#         id: eze-test
#       - name: Write sarif to workspace file.
#         run: |
#           cat > eze.sarif <<'EOF'
#             ${{ steps.eze-test.outputs.sarif_file }}
#           EOF
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: eze.sarif
          category: my-analysis-tool
